clone_folder: c:\gopath\src\github.com\GoogleContainerTools\skaffold
stack: go 1.11

environment:
  GOPATH: c:\gopath

install:
  - appveyor-retry choco install make

build_script:
# TODO: flags
  - make out/skaffold-windows-amd64.exe
  - go build -o out/skaffold-windows-amd64.exe cmd/skaffold/skaffold.go

test_script:
  - go test ./...

artifacts:
  - name: skaffold
    path: out/skaffold-windows-amd64.exe
