steps:

- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/dgageot/skaffold-ci.git']

# Can we retrieve from fork's branch?
- name: gcr.io/cloud-builders/git
  dir: skaffold-ci
  args: ['reset', '--hard', '$COMMIT_SHA']

- name: gcr.io/cloud-builders/docker
  args: ['pull', 'golang:1.11.5-stretch']

- name: golang:1.11.5-stretch
  entrypoint: /bin/bash
  args:
  - -c
  - |
    PARENT_DIR="$$GOPATH/src/github.com/GoogleContainerTools"
    mkdir -p $$PARENT_DIR
    ln -s /workspace/skaffold-ci $$PARENT_DIR/skaffold
    cd $$PARENT_DIR/skaffold

    echo "REPO_NAME $$REPO_NAME"
    echo "BRANCH_NAME $$BRANCH_NAME"
    echo "TAG_NAME $$TAG_NAME"
    echo "REVISION_ID $$REVISION_ID"
    echo "COMMIT_SHA $$COMMIT_SHA"

    make out/skaffold test
